### ISSUE TITLE
Define SOAP controllers as services

### ISSUE THREAD

**Issue by matteodem** [BeSimple/BeSimpleSoapBundle#101]
Right now I got following code

``` yaml
be_simple_soap:
    cache:
        type:     memory
        lifetime: 86400  # one day
        limit:    5
    services:
        CouponsApi:
            namespace:     https://soap-api.test.com/CouponsApi
            binding:       rpc-literal
            resource:      "@AppBundle/Controller/CouponsController.php"
```

I'd like to rewrite it though to reference a service that is a controller

``` yaml
be_simple_soap:
    cache:
        type:     memory
        lifetime: 86400  # one day
        limit:    5
    services:
        CouponsApi:
            namespace:     https://soap-api.test.com/CouponsApi
            binding:       rpc-literal
            resource:      app_soap._coupons_controller
```

When I do this though I get an internal server error for SOAP calls. What is needed for this to work?
