### ISSUE TITLE
Soap Fault: Server was unable to process request. ---> Object reference not set to an instance of an object. 

### ISSUE THREAD

**Issue by brunolouvem** [BeSimple/BeSimpleSoapBundle#103]
Hello friends, I am having trouble with the following error message when using the bundle:
"Server Was Unable to process request. ---> Object reference not set to an instance of an object."
The WSDL that I am using is: https://ecommerce.userede.com.br/pos_virtual/wskomerci/cap.asmx?WSDL
And the method is: GetAuthorized

I do not understand this error, could help me?

``` php
private function getAuthorized($pp){

        $soapClient = $this->get('besimple.soap.client.komerciapi');

        $transaction = $soapClient->GetAuthorized(
            $pp['TOTAL'],
            $pp['TRANSACAO'],
            $pp['PARCELAS'],
            $pp['FILIACAO'],
            $pp['NUMPEDIDO'],
            $pp['NRCARTAO'],
            $pp['CVC2'],
            $pp['MES'],
            $pp['ANO'],
            $pp['PORTADOR'],
            $pp['IATA'],
            $pp['DISTRIBUIDOR'],
            $pp['CONCENTRADOR'],
            $pp['TAXAEMBARQUE'],
            $pp['ENTRADA'],
            $pp['PAX1'],
            $pp['PAX2'],
            $pp['PAX3'],
            $pp['PAX4'],
            $pp['NUMDOC1'],
            $pp['NUMDOC2'],
            $pp['NUMDOC3'],
            $pp['NUMDOC4'],
            $pp['CONFTXN'],
            $pp['ADD_Data'],''
        );

    }
```

``` yml
be_simple_soap:
    clients:
        KomerciApi:
            # required
            wsdl: https://ecommerce.userede.com.br/pos_virtual/wskomerci/cap.asmx?WSDL
```
