### ISSUE TITLE
Doesn't work document-wrapped style

### ISSUE THREAD

**Issue by Falconazz** [BeSimple/BeSimpleSoapBundle#88]
Doesn't work document-wrapped

config.yml

``` yml
be_simple_soap:
    services:
        soap_v1:
            namespace:     http://localhost/ws/soap_v1
            binding:       document-wrapped #rpc-literal
            resource:      "@Acme/Controller/DemoController.php"
            resource_type: annotation
    cache:
        type:     disk
        lifetime: 86400
        limit:    5
```

DemoController.php

``` php
use BeSimple\SoapBundle\ServiceDefinition\Annotation as Soap;
use Symfony\Component\DependencyInjection\ContainerAware;

class DemoController extends ContainerAware
{
   /**
     * @Soap\Method("hello")
     * @Soap\Param("names", phpType = "string[]")
     * @Soap\Result(phpType = "string")
     */
    public function helloAction(array $names)
    {
        return "Hello ".implode(', ', $names);
    }
}
```

Wsdl

``` xml
<binding name="soap_v1Binding" type="tns:soap_v1PortType">
<soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="rpc"/>
<operation name="hello">
<soap:operation soapAction="http://localhost/ws/soap_v1hello"/>
<input>
<soap:body use="literal" namespace="http://localhost/ws/soap_v1" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
</input>
<output>
<soap:body use="literal" namespace="http://localhost/ws/soap_v1" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
</output>
</operation>
</binding>
```

client message

``` xml
Envelope xmlns="http://schemas.xmlsoap.org/soap/envelope/">
    <Body>
        <hello xmlns="http://localhost/ws/soap_v1">
            <names><item>one</item><item>two</item></names>
        </hello>
    </Body>
</Envelope>
```

Error message 

``` html
<br />
<b>Fatal error</b>:  Class 'BeSimple\SoapBundle\ServiceBinding\DocumentLiteralWrappedRequestHeaderMessageBinder' not found in <b> 

.../vendor/besimple/soap/src/BeSimple/SoapBundle/WebServiceContext.php</b> on line <b>93</b><br />
```

ServiceConfig BeSimpleSoapBundle/Resources/config/webservice.xml

``` xml
 <parameter key="besimple.soap.binder.request_header.documentwrapped.class">BeSimple\SoapBundle\ServiceBinding\DocumentLiteralWrappedRequestHeaderMessageBinder</parameter>
```

Folder ServiceBinding doesn't contain DocumentLiteralWrappedRequestHeaderMessageBinder.php

This bundle support document-wrapped style ?
