### ISSUE TITLE
Setting binding is ignored and what about version?

### ISSUE THREAD

**Issue by MichalM1** [BeSimple/BeSimpleSoapBundle#95]
I set in config.yml:

``` YAML
be_simple_soap:
    services:
        ImportApi:
            namespace:     http://acme.cz/ws/ImportApi/1.0/
            binding:       document-wrapped
            resource:      "@AcmeBundle/Controller/SoapController.php"
            resource_type: annotation
```

but WSDL is generated with Style: **Rpc/Literal**.

If I modified class **BeSimple\SoapCommon\Definition\Definition** and set default style as SOAP_DOCUMENT, I have got invalid WSDL.

_Note: In one SOAP function I use parameter with ComplexType._

How can I set version (soap **1.1** or **1.2**)?
